---
- name: Configurar OSPFv2 via NETCONF en IOS XE
  hosts: router
  gather_facts: false

  tasks:
    - name: Aplicar configuración OSPF completo
      ansible.netcommon.netconf_config:
        target: running
        commit: true
        content: |
          <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <router>
                <ospf xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ospf">
                  <id>1</id>
                  <router-id>1.1.1.1</router-id>
                  <network>
                    <ip>10.0.1.0</ip>
                    <mask>0.0.0.255</mask>
                    <area>0</area>
                  </network>
                  <network>
                    <ip>10.0.2.0</ip>
                    <mask>0.0.0.255</mask>
                    <area>0</area>
                  </network>
                </ospf>
              </router>
            </native>
          </config>

    - name: Validar zonas y vecindad OSPF
      ansible.netcommon.netconf_get:
        source: running
        filter: |
          <filter>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <router>
                <ospf/>
              </router>
            </native>
          </filter>
      register: ospf_config

    - name: Mostrar configuración OSPF reportada
      debug:
        msg: "{{ ospf_config }}"

