---
- name: Configurar OSPFv2 via NETCONF en IOS XE
  hosts: router
  gather_facts: false
  connection: ansible.netcommon.netconf
  vars:
    ansible_port: 830

  tasks:
    - name: Configurar interfaces L3 (IP y estado) vía NETCONF
      ansible.netcommon.netconf_config:
        commit: true
        default_operation: merge
        content: |
          <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <interface>
                <GigabitEthernet>
                  <name>2</name>
                  <shutdown operation="remove"/>
                  <ip>
                    <address>
                      <primary>
                        <address>192.168.100.1</address>
                        <mask>255.255.255.0</mask>
                      </primary>
                    </address>
                  </ip>
                </GigabitEthernet>
                <GigabitEthernet>
                  <name>3</name>
                  <shutdown operation="remove"/>
                  <ip>
                    <address>
                      <primary>
                        <address>192.168.120.1</address>
                        <mask>255.255.255.0</mask>
                      </primary>
                    </address>
                  </ip>
                </GigabitEthernet>
              </interface>
            </native>
          </config>

    - name: Aplicar configuración OSPFv2
      ansible.netcommon.netconf_config:
        target: running
        commit: true
        content: |
          <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <router>
                <router-ospf xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ospf">
                  <ospf>
                    <process-id>
                      <id>1</id>
                      <network>
                        <ip>192.168.100.0</ip>
                        <wildcard>0.0.0.255</wildcard>
                        <area>0</area>
                      </network>
                      <network>
                        <ip>192.168.120.0</ip>
                        <wildcard>0.0.0.255</wildcard>
                        <area>0</area>
                      </network>
                      <router-id>3.3.3.3</router-id>
                    </process-id>
                  </ospf>
                </router-ospf>
              </router>
            </native>
          </config>

    - name: Guardar configuración en memoria
      ansible.netcommon.netconf_rpc:
        rpc: >
          <cisco-ia:save-config xmlns:cisco-ia="http://cisco.com/ns/yang/cisco-ia"/>
