- name: Validar conectividad ICMP
  hosts: router
  gather_facts: false

  tasks:
    - name: Ping a router loopback
      connection: ansible.netcommon.network_cli
      ios_ping:
        dest: "{{ hostvars['router'].ansible_host }}"
        count: 3
      register: ping_result

    - debug:
        msg: "Ping exitoso: {{ ping_result }}"
