---
- name: Validar configuración OSPFv2 en IOS XE
  hosts: router
  gather_facts: false

  tasks:
    - name: Validar zonas y vecindad OSPF
      ansible.netcommon.netconf_get:
        source: running
        filter: |
          <filter>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <router>
                <ospf/>
              </router>
            </native>
          </filter>
      register: ospf_config

    - name: Mostrar configuración OSPF reportada
      debug:
        msg: "{{ ospf_config }}"


