---
- name: Mostrar configuración OSPFv2 via NETCONF en IOS XE
  hosts: router
  gather_facts: false
  connection: ansible.netcommon.netconf
  vars:
    ansible_port: 830

  tasks:
    - name: Get Interface Config
      ansible.netcommon.netconf_get:
        source: running
        display: pretty
        filter: |
          <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
            <interface>
              <GigabitEthernet>
                <name>1</name>
              </GigabitEthernet>
              <GigabitEthernet>
                <name>2</name>
              </GigabitEthernet>
            </interface>
          </native>
      register: interface_config

    - name: Print Interface Data
      debug:
        msg: "{{ interface_config.stdout }}"

    - name: Get OSPF Neighbor Info
      ansible.netcommon.netconf_get:
        source: running
        display: xml
      register: ospf_neighbors

    - name: Get OSPF neighbor data using CLI over NETCONF
      ansible.netcommon.netconf_rpc:
        content: |
          <cisco-ia:exec-command xmlns:cisco-ia="http://cisco.com/ns/yang/cisco-ia">
            <cisco-ia:command>show ip ospf neighbor</cisco-ia:command>
          </cisco-ia:exec-command>
      register: ospf_neighbors

    - name: Print OSPF Neighbor Data
      debug:
        msg: "{{ ospf_neighbors.stdout }}"

    # - name: Print OSPF Neighbor Data
    #   copy:
    #     content: "{{ ospf_neighbors.stdout }}" 
    #     dest: ./configs/{{ inventory_hostname }}-Interface-config.xml
