---
- name: Mostrar configuración OSPFv2 via NETCONF en IOS XE
  hosts: router
  gather_facts: false
  connection: ansible.netcommon.netconf
  vars:
    ansible_port: 830

  tasks:
    - name: Get Interface Config
      ansible.netcommon.netconf_get:
        source: running
        display: pretty

- name: Mostrar configuración y vecinos OSPFv2 vía comandos CLI en IOS XE
  hosts: router
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Obtener configuración de interfaces relevantes
      cisco.ios.ios_command:
        commands:
          - show running-config interface GigabitEthernet1
          - show running-config interface GigabitEthernet2
      register: interface_config

    - name: Mostrar configuración de interfaces
      debug:
        var: interface_config.stdout_lines

    - name: Obtener vecinos OSPF
      cisco.ios.ios_command:
        commands:
          - show ip ospf neighbor
      register: ospf_neighbors

    - name: Mostrar vecinos OSPF
      debug:
        var: ospf_neighbors.stdout_lines

    # Optional: Guardar resultado en archivo local
    # - name: Guardar vecinos OSPF en archivo
    #   copy:
    #     content: "{{ ospf_neighbors.stdout | join('\n') }}"
    #     dest: "./configs/{{ inventory_hostname }}-ospf-neighbors.txt"

