---
- name: Mostrar configuración OSPFv2 via NETCONF en IOS XE
  hosts: router
  gather_facts: false
  connection: ansible.netcommon.netconf
  vars:
    ansible_port: 830

  tasks:
    - name: Get Interface Config
      ansible.netcommon.netconf_get:
        source: running
        display: pretty
        filter: |
          <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
            <interface>
              <GigabitEthernet>
                <name>1</name>
              </GigabitEthernet>
              <GigabitEthernet>
                <name>2</name>
              </GigabitEthernet>
            </interface>
          </native>
      register: interface_config

    - name: Print Interface Data
      debug:
        msg: "{{ interface_config.stdout }}"

    - name: Get OSPF Neighbor Info
      ansible.netcommon.netconf_get:
        source: running
        display: xml
        filter: |
          <ospf-oper-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ospf-oper">
              <ospf-state>
                <op-mode/>
                <ospf-instance>
                  <process-id/>
                </ospf-instance>
              </ospf-state>
            </ospf-oper-data>
      register: ospf_neighbors

    - name: Print OSPF Neighbor Data
      debug:
        msg: "{{ ospf_neighbors.stdout }}"
